// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq_uGCg3UcW7TVUyZe3jZYVm1rZ7zYHbc',
    appId: '1:1010587351277:web:23232d8592d2a33a58f4e4',
    messagingSenderId: '1010587351277',
    projectId: 'foodwheelsfast-c2fcd',
    authDomain: 'foodwheelsfast-c2fcd.firebaseapp.com',
    storageBucket: 'foodwheelsfast-c2fcd.firebasestorage.app',
    measurementId: 'G-VP85TFY8Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUQoU59XFPTTXGscVClCPSLMGdZp4L9Ac',
    appId: '1:1010587351277:android:a4c9e4d7c8ea3ebb58f4e4',
    messagingSenderId: '1010587351277',
    projectId: 'foodwheelsfast-c2fcd',
    storageBucket: 'foodwheelsfast-c2fcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeI9HOfgybS2_YXhQt-PoGeA2OVlevWto',
    appId: '1:1010587351277:ios:3ad2956f8432e05e58f4e4',
    messagingSenderId: '1010587351277',
    projectId: 'foodwheelsfast-c2fcd',
    storageBucket: 'foodwheelsfast-c2fcd.firebasestorage.app',
    iosBundleId: 'com.example.pnFlFoodyUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeI9HOfgybS2_YXhQt-PoGeA2OVlevWto',
    appId: '1:1010587351277:ios:3ad2956f8432e05e58f4e4',
    messagingSenderId: '1010587351277',
    projectId: 'foodwheelsfast-c2fcd',
    storageBucket: 'foodwheelsfast-c2fcd.firebasestorage.app',
    iosBundleId: 'com.example.pnFlFoodyUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq_uGCg3UcW7TVUyZe3jZYVm1rZ7zYHbc',
    appId: '1:1010587351277:web:8f1c09b284e7b3f358f4e4',
    messagingSenderId: '1010587351277',
    projectId: 'foodwheelsfast-c2fcd',
    authDomain: 'foodwheelsfast-c2fcd.firebaseapp.com',
    storageBucket: 'foodwheelsfast-c2fcd.firebasestorage.app',
    measurementId: 'G-G7F3YVWGW0',
  );

}